### ISSUE TITLE
WARNING:galaxy.model:Datatype class not found for extension 'map'

### ISSUE THREAD

**Issue by lparsons** [vanOpijnenLab/MAGenTA#2]
When running the enhanced bowtie mapper, I get the error:

    WARNING:galaxy.model:Datatype class not found for extension 'map'

Do I need to add this datatype to Galaxy somehow? I'm assuming the calculate fitness script requires this format, and SAM formatted data will not work. Is that correct?

**Comment by kaymccoy** [comment]
Yes, the calc fit script relies on its input being in .map format. This warning is probably the result of an update to Galaxy, as I just did a test run on the van Opijnen lab instance with the enhanced bowtie mapper and it ran without any warnings; I'm guessing now you need to explicitly add datatypes to Galaxy otherwise it'll return a warning if it doesn't already "know" the type. I don't really understand the reasoning behind that, but I have found a page on how to do it: https://galaxyproject.org/admin/datatypes/adding-datatypes/ Sorry about the inconvenience!
